# Generated by Django 4.2.6 on 2023-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_questiontype_code_alter_questiontype_name'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(blank=True, to='question.question'),
        ),
    ]
